app/client/src/ce/constants/messages.ts
app/client/src/components/editorComponents/ActionCreator/Fields.tsx
app/client/src/components/editorComponents/ActionCreator/constants.ts
app/client/src/components/editorComponents/ActionCreator/index.tsx
app/client/src/entities/DataTree/actionTriggers.ts
app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts
app/client/src/sagas/ActionExecution/AddMessageHandlerSaga.ts
app/client/src/utils/autocomplete/EntityDefinitions.ts
app/client/src/workers/Actions.ts

>https://manabie.atlassian.net/browse/LT-27896
> Please …

[LT-27896] add post message handler

---

app/client/src/sagas/ActionExecution/AddMessageHandlerSaga.ts

allow local appsmith domain

---

deploy/docker/entrypoint.sh

[LT-28346] update entrypoint mongodb

---

app/client/src/pages/AppViewer/AppPage.tsx
app/client/src/pages/AppViewer/PageMenu.tsx
app/client/src/pages/AppViewer/index.tsx

> https://manabie.atlassian.net/browse/LT-29624
> Please …

[LT-29624] root js

---

app/client/src/pages/AppViewer/AppPage.tsx

[LT-29624] move addmessage outside

---

app/client/src/pages/AppViewer/index.tsx
app/client/src/widgets/BaseInputWidget/component/index.tsx
app/client/src/widgets/BaseInputWidget/constants.ts
app/client/src/widgets/InputWidget/component/index.tsx
app/client/src/widgets/InputWidget/constants.ts
app/client/src/widgets/InputWidget/widget/index.tsx
app/client/src/widgets/InputWidgetV2/component/index.tsx
app/client/src/widgets/InputWidgetV2/widget/index.tsx

add input color

---

app/client/src/widgets/InputWidgetV2/widget/index.tsx

update input color default

---

app/client/src/pages/AppViewer/AppPage.tsx
app/client/src/pages/AppViewer/index.tsx

move addEventListener to root page

---

app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
app/client/src/pages/AppViewer/index.tsx
app/client/src/sagas/EvaluationsSaga.ts

[LT-29624] global js token

---

app/client/src/pages/AppViewer/index.tsx

>
https://manabie.atlassian.net/browse/LT-30256
> Please …

feature: Force update background color to white

---

app/client/src/sagas/EvaluationsSaga.ts
app/client/src/sagas/WebsocketSagas/handleAppLevelSocketEvents.tsx

callback postmessage

---

app/client/src/widgets/TableWidgetV2/widget/index.tsx

order colums table

---

app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Applications/index.tsx

revoke delete app role

---

app/client/package.json
app/client/public/index.html
app/client/src/pages/common/PageLoadingBar.tsx

>
Media
https://user-images.githubusercontent.com/91859509/206072278-9a4a9256-b8b6-41e8-bebb-1c …

[LT-32086]feature: Customize loading iframe appsmith

---

app/client/src/ce/constants/ApiConstants.tsx

>
https://manabie.atlassian.net/browse/LT-31609
> Add type to support show snackbar in BO
Media

[LT-31609]feature: Add type post message show snackbar

---

app/client/.eslintrc.json
app/client/package.json
app/client/src/sagas/WebsocketSagas/handleAppLevelSocketEvents.tsx
app/client/src/widgets/TableWidget/component/Constants.ts
app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx
app/client/src/widgets/TableWidget/widget/derived.js
app/client/src/widgets/TableWidgetV2/component/Constants.ts
app/client/src/widgets/TableWidgetV2/component/Table.tsx
app/client/src/widgets/TableWidgetV2/component/TableBody/Row.tsx
app/client/src/widgets/TableWidgetV2/component/TableBody/index.tsx
app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/BasicCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/ButtonCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/CheckboxCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/EditActionsCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/EmptyCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/IconButtonCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/ImageCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/MenuButtonCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/PlainTextCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/SelectCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/SwitchCell.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/VideoCell.tsx
app/client/src/widgets/TableWidgetV2/component/header/actions/index.tsx
app/client/src/widgets/TableWidgetV2/component/index.tsx
app/client/src/widgets/TableWidgetV2/index.ts
app/client/src/widgets/TableWidgetV2/widget/derived.js
app/client/src/widgets/TableWidgetV2/widget/index.tsx
app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts

>
> https://manabie.atlassian.net/browse/LT-31616
> Customize UI and behavior of table to sync BO
Media
https://user-images.githubusercontent.com/91859509/206358112-e911dce7-09f3-4f7e-8ad6-94a58eef5f77.mp4

[LT-31616]Feature: custome table widget

---

app/client/src/ce/variants/aic.ts
app/client/src/ce/variants/config.ts
app/client/src/ce/variants/e2e.ts
app/client/src/ce/variants/ga.ts
app/client/src/ce/variants/jprep.ts
app/client/src/ce/variants/manabie.ts
app/client/src/ce/variants/renseikai.ts
app/client/src/ce/variants/synersia.ts
app/client/src/ce/variants/tokyo.ts
app/client/src/entities/Engine/index.ts
app/client/src/pages/AppViewer/AppPage.tsx
app/client/src/sagas/EvaluationsSaga.ts
app/client/src/widgets/TableWidgetV2/component/header/actions/index.tsx

dynamic datasource

---

app/client/src/ce/variants/aic.ts
app/client/src/ce/variants/config.ts
app/client/src/ce/variants/e2e.ts
app/client/src/ce/variants/ga.ts
app/client/src/ce/variants/jprep.ts
app/client/src/ce/variants/manabie.ts
app/client/src/ce/variants/renseikai.ts
app/client/src/ce/variants/synersia.ts
app/client/src/ce/variants/tokyo.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java

https://manabie.atlassian.net/browse/LT-32806

disable delete app feature

---

app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts

feat: add code comment

---

app/client/src/widgets/TextWidget/component/index.tsx
app/client/src/widgets/TextWidget/widget/index.tsx

>  Customize text widget, add custom option border radius and box shadow

[LT-32337]feature: Customize add property box shadow and border radius for text widget

---

app/client/src/widgets/TableWidgetV2/component/Table.tsx
app/client/src/widgets/TableWidgetV2/component/TableBody/TableBodyHasNoData.tsx
app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx

- Customize table widget have no data

refactor: Custom table have no data

---

app/client/src/widgets/TextWidget/widget/index.tsx

> Support translation for text widget appsmith
Media
https://user-images.githubusercontent.com/91859509/209909900-b4c4ac55-24c3-4cce-9c32-024d2ca08210.mp4

[LT-33569] feature: Translate text widget

---

app/client/src/sagas/ActionExecution/PluginActionSaga.ts

retry proxy

---

app/client/src/ce/variants/aic.ts
app/client/src/ce/variants/config.ts
app/client/src/ce/variants/e2e.ts
app/client/src/ce/variants/ga.ts
app/client/src/ce/variants/jprep.ts
app/client/src/ce/variants/manabie.ts
app/client/src/ce/variants/renseikai.ts
app/client/src/ce/variants/synersia.ts
app/client/src/ce/variants/tokyo.ts

new config urls

---

app/client/src/index.css
app/client/src/theme/wds.css
app/client/src/widgets/BaseInputWidget/component/index.tsx
app/client/src/widgets/BaseInputWidget/constants.ts
app/client/src/widgets/BaseInputWidget/index.ts
app/client/src/widgets/BaseInputWidget/widget/index.tsx
app/client/src/widgets/InputWidgetV2/component/index.tsx
app/client/src/widgets/InputWidgetV2/widget/index.tsx

> Custom UI of input widget 
Media
https://user-images.githubusercontent.com/91859509/211716918-355465b6-c492-43a9-82f7-14ab2c8477ac.mp4

[LT-33575] feature: Update UI input follow MUI UI

---

app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx

Fix auto generate ticket number

---

app/client/src/pages/AppViewer/index.tsx

fix bug undefined font

---

app/client/src/api/ActionAPI.tsx
app/client/src/ce/constants/ApiConstants.tsx
app/client/src/entities/Engine/index.ts

post message loaded

---

app/client/src/widgets/ChartWidget/component/index.tsx
app/client/src/widgets/MapChartWidget/component/index.tsx

https://manabie.atlassian.net/browse/LT-45012

[LT-45012] add other theme for chart widget

---

app/client/src/widgets/BaseInputWidget/component/index.tsx

fix input with icon

---

app/client/src/widgets/ButtonWidget/component/index.tsx
app/client/src/widgets/ButtonWidget/widget/index.tsx

https://manabie.atlassian.net/browse/LT-43667

support edit button text size

---

app/client/src/widgets/ButtonGroupWidget/component/index.tsx
app/client/src/widgets/ButtonGroupWidget/widget/index.tsx

https://manabie.atlassian.net/browse/LT-45056

 [LT-45056] support change color text button group

---

app/client/src/widgets/SelectWidget/component/index.styled.tsx
app/client/src/widgets/SelectWidget/component/index.tsx
app/client/src/widgets/SelectWidget/widget/index.tsx

https://manabie.atlassian.net/browse/LT-43674

[select widget] support show error message

---

app/client/src/widgets/FilePickerWidgetV2/component/index.tsx
app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx

[filepicker] add helptext

---

app/client/src/widgets/TableWidgetV2/component/Table.tsx
app/client/src/widgets/TableWidgetV2/component/cellComponents/BasicCell.tsx
app/client/src/widgets/TableWidgetV2/component/chip/index.tsx
app/client/src/widgets/TableWidgetV2/component/header/actions/index.tsx
app/client/src/widgets/TableWidgetV2/component/index.tsx
app/client/src/widgets/TableWidgetV2/widget/index.tsx
app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts
app/client/src/widgets/TextWidget/component/index.tsx
app/client/src/widgets/TextWidget/widget/index.tsx

https://manabie.atlassian.net/browse/LT-43671
https://manabie.atlassian.net/browse/LT-43672

[LT-43672] table chip filtered

---

app/client/src/widgets/TextWidget/component/index.tsx
app/client/src/widgets/TextWidget/widget/index.tsx

[LT-43666] add some text common style in manabie

---

app/client/src/widgets/ButtonGroupWidget/component/index.tsx
app/client/src/widgets/ButtonGroupWidget/constants.ts
app/client/src/widgets/ButtonGroupWidget/index.ts
app/client/src/widgets/ButtonGroupWidget/widget/index.tsx

feature: Support customize size of button dropdown

---

app/client/src/sagas/ActionExecution/PluginActionSaga.ts

feat-remove-retry
